server:
  port: 8802
spring:
  application:
    name: "user-service"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
    username: music
    password: music
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "http://authorization-server:8801/oauth2/introspect"
          client-secret: 123456
          client-id: alone-ship